name: stormberry
description: Access your postgres database effortlessly from dart code.
version: 0.7.0
repository: https://github.com/schultek/stormberry
issue_tracker: https://github.com/schultek/stormberry/issues

dependencies:
  analyzer: ^4.7.0
  build: ^2.3.1
  collection: ^1.16.0
  crypto: ^3.0.2
  dart_style: ^2.2.4
  postgres: ^2.5.1
  source_gen: ^1.2.3
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.6

environment:
  sdk: '>=2.12.0 <3.0.0'
