name: stormberry
description: A strongly-typed postgres ORM to provide easy bindings between your dart classes and postgres database.
version: 0.13.1
repository: https://github.com/schultek/stormberry
issue_tracker: https://github.com/schultek/stormberry/issues
funding:
  - https://github.com/sponsors/schultek

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^5.2.0
  args: ^2.3.1
  build: ^2.3.1
  collection: ^1.16.0
  crypto: ^3.0.2
  dart_style: ^2.2.4
  file: ^6.1.4
  glob: ^2.1.1
  path: ^1.8.2
  postgres: ^2.5.1
  source_gen: ^1.2.3
  yaml: ^3.1.1

dev_dependencies:
  build_resolvers: ^2.1.0
  build_runner: ^2.2.0
  build_test: ^2.1.5
  docker_process: ^1.3.1
  lints: ^2.0.0
  test: ^1.21.0

dependency_overrides:
  postgres:
    git:
      url: https://github.com/isoos/postgresql-dart.git

